<?php
global $_W;
/*
$sql = "
drop table if exists " . tablename('sea_adv') . " ;
drop table if exists " . tablename('sea_carrier') . " ;
drop table if exists " . tablename('sea_category') . " ;
drop table if exists " . tablename('sea_commission_apply') . " ;
drop table if exists " . tablename('sea_commission_clickcount') . " ;
drop table if exists " . tablename('sea_commission_level') . " ;
drop table if exists " . tablename('sea_commission_log') . " ;
drop table if exists " . tablename('sea_commission_shop') . " ;
drop table if exists " . tablename('sea_designer') . " ;
drop table if exists " . tablename('sea_dispatch') . " ;
drop table if exists " . tablename('sea_express') . " ;
drop table if exists " . tablename('sea_feedback') . " ;
drop table if exists " . tablename('sea_goods') . "; 
drop table if exists " . tablename('sea_goods_comment') . " ;
drop table if exists " . tablename('sea_goods_option') . " ;
drop table if exists " . tablename('sea_goods_param') . " ;
drop table if exists " . tablename('sea_goods_spec') . " ;
drop table if exists " . tablename('sea_goods_spec_item') . " ;
drop table if exists " . tablename('sea_member') . " ;
drop table if exists " . tablename('sea_member_address') . " ;
drop table if exists " . tablename('sea_member_cart') . " ;
drop table if exists " . tablename('sea_member_favorite') . " ;
drop table if exists " . tablename('sea_member_group') . " ;
drop table if exists " . tablename('sea_member_history') . " ;
drop table if exists " . tablename('sea_member_level') . " ;
drop table if exists " . tablename('sea_member_log') . " ;
drop table if exists " . tablename('sea_member_message_template') . " ;
drop table if exists " . tablename('sea_notice') . " ;
drop table if exists " . tablename('sea_order') . " ;
drop table if exists " . tablename('sea_order_comment') . " ;
drop table if exists " . tablename('sea_order_goods') . " ;
drop table if exists " . tablename('sea_order_refund') . " ;
drop table if exists " . tablename('sea_perm_log') . " ;
drop table if exists " . tablename('sea_perm_plugin') . "; 
drop table if exists " . tablename('sea_perm_role') . " ;
drop table if exists " . tablename('sea_perm_user') . " ;
drop table if exists " . tablename('sea_plugin') . " ;
drop table if exists " . tablename('sea_poster') . " ;
drop table if exists " . tablename('sea_poster_log') . " ;
drop table if exists " . tablename('sea_poster_qr') . " ;
drop table if exists " . tablename('sea_poster_scan') . " ;
drop table if exists " . tablename('sea_saler') . " ;
drop table if exists " . tablename('sea_store') . " ;
drop table if exists " . tablename('sea_sysset') . " ;
drop table if exists " . tablename('sea_creditshop_adv') . " ;
drop table if exists " . tablename('sea_creditshop_category') . " ;
drop table if exists " . tablename('sea_creditshop_goods') . " ;
drop table if exists " . tablename('sea_creditshop_log') . " ;
drop table if exists " . tablename('sea_virtual_category') . " ;
drop table if exists " . tablename('sea_virtual_data') . " ;
drop table if exists " . tablename('sea_virtual_type') . " ;
drop table if exists " . tablename('sea_designer_menu') . " ;
drop table if exists " . tablename('sea_article') . " ;
drop table if exists " . tablename('sea_article_category') . " ;
drop table if exists " . tablename('sea_article_log') . " ;
drop table if exists " . tablename('sea_article_report') . " ;
drop table if exists " . tablename('sea_article_share') . " ;
drop table if exists " . tablename('sea_article_sys') . " ;
drop table if exists " . tablename('sea_postera_log') . " ;
drop table if exists " . tablename('sea_postera_qr') . " ;
drop table if exists " . tablename('sea_coupon') . " ;
drop table if exists " . tablename('sea_coupon_category') . " ;
drop table if exists " . tablename('sea_coupon_data') . " ;
drop table if exists " . tablename('sea_coupon_guess') . " ;
drop table if exists " . tablename('sea_coupon_log') . " ;
";
pdo_query($sql);
*/